# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-20 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0003_auto_20180420_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewinfo',
            options={'verbose_name': '冲煮信息', 'verbose_name_plural': '冲煮信息'},
        ),
    ]
